vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        adopter_news_images:
            uri_prefix: /uploads/adopter_news
            upload_destination: '%kernel.project_dir%/public/uploads/adopter_news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
